---
title: "Overview of Process for Generating LHJ Population Data"
author: "CDPH/LHJ Population Task Force"
date: "`r format(Sys.Date(), '%B %d, %Y')`"
output: html_document
editor_options: 
  markdown: 
    wrap: 72
---

```{r include=FALSE}

# Kniting Options
knitr::opts_chunk$set(eval = FALSE)
```

This system of data and RMarkdown file extracts and processes population
data to generate data sets with sex-age-race/ethnicity estimates for all
58 California **counties**; the three city-based **local health
jurisdictions (LHJs)** of Berkeley, Long Beach, and Pasadena; and the
two respective county-less-city LHJs of Alameda LHJ and Los Angeles LHJ.

**Data Files used:**

-   **DOF-E4**: Department of Finance's (DOF) city and county population
    totals (January estimates)

-   **DOF-E6**: DOF county population totals (July estimates)

-   DOF county population (July estimates/projections) by single year of
    age, race/ethnicity, and sex - Referred to as **DOF-ARS or DOF-P3**

    -   Annual Intercensal Population Estimates by Race/Ethnicity with
        Age and Gender Detail

    -   Complete P-3 Race/Ethnicity and Sex by Age for California and
        Counties

        -   Vintage 2023 (2024.3.8) version - For 2020-2023 population

        -   Vintage 2020 (2021.7.14) version - For 2010-2023 population

-   US Decennial census county and city population data for census
    years, by single year of age, race/ethnicity, and sex. Referred to
    as **Census**

**The core concept is:**

1.  Get **DOF-E4** and **DOF-E6** data to calculate total population
    July estimates for LHJs. Referred to as **LHJ-Total**
2.  Get **DOF-ARS** data and adjust the county ARS population estimates
    to the "better" county July 1st estimates (in **LHJ-Total)**.
    Referred to as **DOF-ARS-Adjusted**
3.  Get **Census** data, and calculate the the proportion of the
    city-level ARS strata to the population of the corresponding
    county-level ARS strata.
4.  Apply the census proportions to their respective
    **DOF-ARS-Adjusted** county-level ARS strata population to get LHJ
    ARS population estimates.
5.  Adjust the LHJ ARS population estimates to July.
6.  Export LHJ-level age-race-sex population data

**Additional key concepts include:**

-   "Other" race is a category in the Decennial Census data but not in
    the other data sources. Therefore, "Other" race category data in the
    decennial census are redistributed to the other race categories.

**Exported files (saved as both .RDS and .csv) in the finalPopData/
folder include:**

-   lhj-population-ars-2000-2023

    -   Variables:

        -   county_lhj

        -   year

        -   sex

        -   age

        -   race\_

        -   population

    -   Note: This is the recommended file to use for trends.

        -   DOF-P3 Vintage 2020 (2021.7.14) version used for 2010-2023
            population

-   lhj-population-ars-2020-2023

    -   Same variables as in "lhj-population-ars-2000-2023"
    -   Note: This is the recommended file to use when only displaying
        data in recent years.
        -   DOF P-3 Vintage 2023 (2024.3.8) version used for 2020-2023
            population

These LHJ population data are generated by a series of R markdown files.
For technical users, the markdown files contain all code and
supplemental documentation for the processes. For general users, each
markdown file generates an html file that provides a higher level
description and documentation of the processes, including the
intermediate and/or final output files generated.

**Purpose of each file is described below:**

**1a-Process-Historical-Raw-Data.Rmd:** processes *historical* county-
and city-level DOF (up-to 2010) and Census Decennial (2000, 2010) data.
This file never needs to be executed again.

**1b-Process-Current-Raw-Data.Rmd:** processes *current* county- and
city-level DOF (2010-2023) and Census Decennial (2020) data. This file
must be maintained and re-executed whenever a new population data file
(either from DOF or Census Decennial) is released.

**2-Create-LHJ-Population-Total.Rmd:** generates a data file with total
July LHJ population estimates, which then is used in
3-Create-LHJ-Population-ARS.Rmd.

**3-Create-LHJ-Population-ARS.Rmd** generates two final data files which
contain single years of age by race/ethnicity by sex population
estimates for LHJs. One data file contains estimates from 2000-2023 and
is recommended for trends. The other data file contains estimates from
2020-2023 and is recommended for reporting data on recent years only.
Both files are saved as .csv and .RDS in finalPopData/:

-   lhj-pop-ars-2000-2023
-   lhj-pop-ars-2020-2023
